# -*- coding: utf-8 -*-
"""Python para Dados - Desafio Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EU6kybcUzO2ql_32idoDL244vY75eWZy
"""

import pandas as pd
import numpy as np

df = pd.read_csv("saude_do_sono_estilo_vida.csv")

df.head()

substituicoes = {'ID':'Identificação', 'Ocupação': 'Profissão', "Pressão sanguíneaaaa" : "Pressão sanguínea", "Categoria BMI": "Categoria IMC" }

df = df.rename(substituicoes, axis = 1)

df

"""2. Qual é a média, a moda e a mediana de horas de sono para cada uma
das profissões? [‘mean’, np.median, pd.Series.mod]
"""

profissao_duracao_sono=df.groupby("Profissão")["Duração do sono"]

profissao_duracao_sono_Media= profissao_duracao_sono.mean()
profissao_duracao_sono_Media

profissao_duracao_sono_Mediana = profissao_duracao_sono.median()

mediana_total = np.median(profissao_duracao_sono_Mediana)

mediana_total

"""3-Das pessoas que atuam com engenharia de software qual a
porcentagem de obesos?
"""

profissao_duracao_sono_Moda = profissao_duracao_sono.agg(pd.Series.mode)

profissao_duracao_sono_Moda

"""Das pessoas que atuam com engenharia de software qual a
porcentagem de obesos?
"""

df
Profissão_por_peso = df[ ["Profissão","Categoria IMC"] ]
Profissão_por_peso.head(10)

filtro_eng_software= Profissão_por_peso["Profissão"] =="Eng. de Software"

filtro_obesidade= Profissão_por_peso["Categoria IMC"] == "Obesidade"

resultado = Profissão_por_peso[filtro_eng_software & filtro_obesidade]

len(resultado)

porcentagem_eng_obesos =(len(resultado)/len(filtro_eng_software))*100

porcentagem_eng_obesos

eng_obsesos=((Profissão_por_peso["Profissão"] == "Eng. de Software") & (Profissão_por_peso["Categoria IMC"] == "Obesidade")).sum()

eng_obsesos

""" 4- De acordo com os dados, advogar ou ser representante de vendas faz
você dormir menos? (Use o método ‘isin’, considere a média)
"""

# Calcular as médias de horas de sono para todas as profissões
media_todas_profissoes = df['Duração do sono'].mean()

# Verificar se advogados e representantes de vendas dormem mais ou menos que a média
media=df[df['Profissão'].isin(['Advogado(a)', 'Representante de Vendas'])]['Duração do sono'].mean()

media

if media < media_todas_profissoes:
  print("advogar ou ser representante de vendas faz você dormir menos? Sim")
else:
    print("advogar ou ser representante de vendas faz você dormir menos? Não")

"""5-Entre quem fez enfermagem e quem fez medicina, quem tem menos
horas de sono? (Use o método ‘isin’, considere a média)
"""

media_sono_medico = df[df['Profissão'].isin(['Médico(a)'])]['Duração do sono'].mean()
media_sono_medico

media_sono_enfermeiro = df[df['Profissão'].isin([ 'Enfermeiro(a)'])]['Duração do sono'].mean()
 media_sono_enfermeiro

if media_sono_medico < media_sono_enfermeiro:
  print("Médico tem menos horas de sono")
else:
  print("Enfemeiro tem menos horas de sono")

"""6-Faça um subconjunto com as colunas Identificador, Gênero, Idade,Pressão sanguínea e Frequência cardíaca."""

df.loc[:, ['Identificação', 'Gênero', 'Idade', 'Pressão sanguínea', 'Frequência cardíaca']]

"""7-Descubra qual a profissão menos frequente no conjunto. (Use
value_counts)
"""

df['Profissão'].value_counts()

"""8-Quem tem maior pressão sanguínea média, homens ou mulheres?
(Considere a média)
"""

media_por_genero = df.groupby("Gênero")["Pressão sanguínea"].mean()

"""9-É predominante entre os participantes dormir 8 horas por dia
(considere usar Moda como medida)?

"""

duração_sono =df['Duração do sono'].mode()

duração_sono.apply(lambda x: x >= 8)

