# -*- coding: utf-8 -*-
"""visualizacao_histograma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvxNxrSz8x7kpsiNN-8gG0BQoGnfNvZm
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    'Produto': ['A', 'B', 'C', 'D', 'E'],
    'Vendas': [100, 150, 200, 120, 180]
}
df = pd.DataFrame(data)

# Visualizando a distribuição de vendas usando um histograma
plt.figure(figsize=(8, 6))
sns.histplot(data=df, x='Vendas', bins=5, kde=True, color='skyblue')
plt.title('Distribuição de Vendas')
plt.xlabel('Vendas')
plt.ylabel('Frequência')
plt.show()

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from tabulate import tabulate

# Criando dados de exemplo
data = {
    'Produto': ['A', 'B', 'C', 'D', 'E'],
    'Vendas': [100, 150, 200, 120, 180]
}
df = pd.DataFrame(data)

# Criando um gráfico de barras
plt.figure(figsize=(8, 6))
plt.bar(df['Produto'], df['Vendas'], color='skyblue')
plt.title('Vendas por Produto')
plt.xlabel('Produto')
plt.ylabel('Vendas')

# Criando um DataFrame para a tabela
table_str = tabulate(df, headers='keys', tablefmt='grid')

# Gerando um relatório em PDF
with PdfPages('relatorio.pdf') as pdf:
    # Adicionando o gráfico ao PDF
    pdf.savefig()
    plt.close()

    # Escrevendo a tabela no PDF
    pdf.attach_note('\n\nTabela de Vendas\n\n' + table_str)

    files.download('relatorio.pdf')